const { a, b: c } = _import_1(dependencies["1"], ["a", "b"], "1", "dependencies.1", false);
const d = _import_1(dependencies["2"], [], "2", "dependencies.2", false);
const _a = _import_1(dependencies["5"], [], "5", "dependencies.5", false);
export { _a as e };
const { x: _b, y: _c, z: _d } = _import_1(dependencies["6"], ["x", "y", "z"], "6", "dependencies.6", false);
export { _b as x, _c as y, _d as z };
console.log(a, c, d);
"import \"3\" is eliminated because it expected to have no side effects in UMD transform.";
"import \"4\" is eliminated because it expected to have no side effects in UMD transform.";
import { _import as _import_1 } from "https://cdn.jsdelivr.net/npm/@magic-works/ttypescript-browser-like-import-transformer@2.3.0/es/ttsclib.min.js";
